AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create an Elastic Container Repository. Initial Configuration.
  Author: Arun.Chunduru'

Parameters:    # =============[ PARAMETERS ]==========================

  pRepositoryName:
    Description: Elastic Container Repository Name
    Type: String
    Default: 'mynissan'
  
  pScanOnPush:
    Description: Scan the Image On Push
    Default: 'true'
    Type: String

Resources:     # ==============[ RESOURCES ]==========================

  ECRRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref pRepositoryName
      ImageScanningConfiguration: 
        scanOnPush: !Ref pScanOnPush	
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action: 
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'
      Tags:
        - Key: technical.contact
          Value: sutantra.2019@gmail.com      
        - Key: application.owner
          Value: Sutantra
        - Key: application.name
          Value: CRMIS-Search
        - Key: module.name
          Value: CRMIS
          
Outputs:      # ==============[ OUTPUTS ]==========================

  ECRArn:
    Description: Repository ARN
    Value: !GetAtt ECRRepository.Arn
